---
- name: "update and upgrade."
  become: true
  apt:
    update_cache: yes
    upgrade: yes
    cache_valid_time: 3600
- name: "remove unneeded deps."
  become: true
  apt:
    autoremove: yes
- name: "install deps"
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: lastest
    update_cache: yes
- name: "install pm2."
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
    
